site_name: Cybersecurity Handbook
site_description: Programming, Terminal, and CompTIA (CySA+, Security+, Linux+) notes + labs
site_url: https://cekujawa.github.io/cysa-study-kit/
repo_url: https://github.com/cekujawa/cysa-study-kit

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Python:
      - Overview: python/index.md
  - Java:
      - Overview: java/index.md
  - Web (HTML/CSS/JS):
      - Overview: web/index.md
  - Terminal:
      - Overview: terminal/index.md
      - CLI Practice: terminal/cli-practice.md
      - Day 1: terminal/day-1.md
      - Day 2: terminal/day-2.md
      - Day 3: terminal/day-3.md
  - CompTIA:
      - CySA+: comptia/cysa/index.md
      - Security+: comptia/securityplus/index.md
      - Linux+: comptia/linuxplus/index.md
  - Quizzes:
      - Overview: quizzes/index.md
      - Core Concepts: quizzes/core-concepts.md
  - Labs:
      - Overview: labs/index.md
      - Linux Brute Force: labs/linux-bruteforce.md












































(.venv) christiankujawa@Christians-MacBook-Pro-10 cysa-study-kit % 
(.venv) christiankujawa@Christians-MacBook-Pro-10 cysa-study-kit % ls -l
total 16
drwxr-xr-x   5 christiankujawa  staff   160 Sep 15 15:15 cli
drwxr-xr-x  10 christiankujawa  staff   320 Sep 15 15:15 docs
-rw-r--r--   1 christiankujawa  staff  1308 Sep 15 15:19 mkdocs.yml
drwxr-xr-x   4 christiankujawa  staff   128 Sep 15 12:26 pbq
drwxr-xr-x   4 christiankujawa  staff   128 Sep 15 15:15 quizzes
-rw-r--r--   1 christiankujawa  staff   502 Sep 15 13:07 README.md
drwxr-xr-x   5 christiankujawa  staff   160 Sep 15 13:27 reports
drwxr-xr-x  15 christiankujawa  staff   480 Sep 15 15:27 site
(.venv) christiankujawa@Christians-MacBook-Pro-10 cysa-study-kit % 

