name: Deploy MkDocs site

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write   # needed so gh-deploy can push to gh-pages

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MkDocs and plugins
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          # add any extras your mkdocs.yml uses, e.g.:
          # pip install mkdocs-minify-plugin mkdocs-glightbox

      - name: Build (sanity check)
        run: mkdocs build --strict

      - name: Deploy to gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force --message "CI: deploy ${{ github.sha }}"

